// <auto-generated />
using System;
using Hotels.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotels.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hotels.Models.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Bangladesh",
                            Division = "Dhaka",
                            Name = "Dhaka"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Bangladesh",
                            Division = "Chittagong",
                            Name = "Chittagong"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Bangladesh",
                            Division = "Comilla",
                            Name = "Comilla"
                        });
                });

            modelBuilder.Entity("Hotels.Models.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MaxPrice")
                        .HasColumnType("float");

                    b.Property<double>("MinPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancies")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("RoomCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "79/A Commercial Area Airport Rd, Dhaka-1229",
                            CityId = 1,
                            Description = "Luxe, modern lodging offering elegant rooms & suites, plus an infinity pool & chic dining.",
                            MaxPrice = 25000.0,
                            MinPrice = 4000.0,
                            Name = "Le Méridien",
                            Occupancies = 3,
                            Rating = 4.5999999999999996,
                            RoomCount = 44
                        },
                        new
                        {
                            Id = 2,
                            Address = "Shahid Saifuddin Khaled Rd, Chattogram-4000",
                            CityId = 2,
                            Description = "Polished quarters in a contemporary hotel offering an infinity pool, a spa & 3 restaurants.",
                            MaxPrice = 25000.0,
                            MinPrice = 4000.0,
                            Name = "Radisson Blu Chattogram Bay View",
                            Occupancies = 3,
                            Rating = 4.5999999999999996,
                            RoomCount = 44
                        },
                        new
                        {
                            Id = 3,
                            Address = "931 Laksham Rd, Cumilla-3501",
                            CityId = 3,
                            Description = "Laid-back hotel featuring a restaurant & a fitness room, as well as breakfast & parking.",
                            MaxPrice = 25000.0,
                            MinPrice = 4000.0,
                            Name = "OASIS Hotel",
                            Occupancies = 3,
                            Rating = 4.0,
                            RoomCount = 44
                        });
                });

            modelBuilder.Entity("Hotels.Models.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BathroomCount")
                        .HasColumnType("int");

                    b.Property<int>("BedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountedPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DisplayPriceRaw")
                        .HasColumnType("float");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("bit");

                    b.Property<int>("MaxOccupancies")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ServiceCharge")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BathroomCount = 2,
                            BedCount = 3,
                            CheckIn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountedPrice = "",
                            DisplayPrice = "$321",
                            DisplayPriceRaw = 321.35000000000002,
                            HotelId = 1,
                            IsAvailable = true,
                            IsBooked = false,
                            IsFavourite = false,
                            MaxOccupancies = 6,
                            Name = "Studio Apartment",
                            ServiceCharge = 15.0,
                            Type = 8
                        },
                        new
                        {
                            Id = 2,
                            BathroomCount = 2,
                            BedCount = 3,
                            CheckIn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountedPrice = "",
                            DisplayPrice = "$321",
                            DisplayPriceRaw = 321.35000000000002,
                            HotelId = 2,
                            IsAvailable = true,
                            IsBooked = false,
                            IsFavourite = false,
                            MaxOccupancies = 6,
                            Name = "Double Deluxe",
                            ServiceCharge = 15.0,
                            Type = 4
                        },
                        new
                        {
                            Id = 3,
                            BathroomCount = 2,
                            BedCount = 3,
                            CheckIn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountedPrice = "",
                            DisplayPrice = "$321",
                            DisplayPriceRaw = 321.35000000000002,
                            HotelId = 3,
                            IsAvailable = true,
                            IsBooked = false,
                            IsFavourite = false,
                            MaxOccupancies = 6,
                            Name = "Twin Deluxe",
                            ServiceCharge = 15.0,
                            Type = 5
                        });
                });

            modelBuilder.Entity("Hotels.Models.Models.Hotel", b =>
                {
                    b.HasOne("Hotels.Models.Models.City", "City")
                        .WithMany("Hotels")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Hotels.Models.Models.Room", b =>
                {
                    b.HasOne("Hotels.Models.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Hotels.Models.Models.City", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("Hotels.Models.Models.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
