// <auto-generated />
using Hotels.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotels.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hotels.Models.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Bangladesh",
                            Division = "Dhaka",
                            Name = "Dhaka"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Bangladesh",
                            Division = "Chittagong",
                            Name = "Chittagong"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Bangladesh",
                            Division = "Comilla",
                            Name = "Comilla"
                        });
                });

            modelBuilder.Entity("Hotels.Models.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "79/A Commercial Area Airport Rd, Dhaka-1229",
                            CityId = 1,
                            Description = "Luxe, modern lodging offering elegant rooms & suites, plus an infinity pool & chic dining.",
                            Name = "Le Méridien",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 2,
                            Address = "Shahid Saifuddin Khaled Rd, Chattogram-4000",
                            CityId = 2,
                            Description = "Polished quarters in a contemporary hotel offering an infinity pool, a spa & 3 restaurants.",
                            Name = "Radisson Blu Chattogram Bay View",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 3,
                            Address = "931 Laksham Rd, Cumilla-3501",
                            CityId = 3,
                            Description = "Laid-back hotel featuring a restaurant & a fitness room, as well as breakfast & parking.",
                            Name = "OASIS Hotel",
                            Rating = 4.0
                        });
                });

            modelBuilder.Entity("Hotels.Models.Models.Hotel", b =>
                {
                    b.HasOne("Hotels.Models.Models.City", "City")
                        .WithMany("Hotels")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Hotels.Models.Models.City", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
